"""crear tabla comercios

Revision ID: 407eda05e4fa
Revises: 
Create Date: 2026-07-10 21:00:17.844869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407eda05e4fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=150), nullable=False),
    sa.Column('nombre_corto', sa.String(length=80), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('calle', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('piso_departamento', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Enum('prueba', 'activo', 'suspendido', 'inactivo', 'baja', name='estado_comercio'), server_default='prueba', nullable=False),
    sa.Column('zona_horaria', sa.String(length=100), server_default='America/Argentina/Buenos_Aires', nullable=False),
    sa.Column('moneda', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('idioma', sa.String(length=10), server_default='es-AR', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comercios'))
    )
    op.create_index(op.f('ix_comercios_cuit'), 'comercios', ['cuit'], unique=False)
    op.create_index(op.f('ix_comercios_slug'), 'comercios', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comercios_slug'), table_name='comercios')
    op.drop_index(op.f('ix_comercios_cuit'), table_name='comercios')
    op.drop_table('comercios')
    # ### end Alembic commands ###
