"""crear metodos de entrega

Revision ID: 660a1332d8db
Revises: 407eda05e4fa
Create Date: 2026-07-10 23:46:03.662343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660a1332d8db'
down_revision: Union[str, Sequence[str], None] = '407eda05e4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "metodos_entrega",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.String(length=100), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "fecha_alta",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_ultima_modificacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "orden >= 0",
            name=op.f("ck_metodos_entrega_orden_no_negativo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metodos_entrega")),
        sa.UniqueConstraint("codigo", name=op.f("uq_metodos_entrega_codigo")),
    )

    op.create_index(
        op.f("ix_metodos_entrega_codigo"),
        "metodos_entrega",
        ["codigo"],
        unique=True,
    )

    op.create_table(
        "comercio_metodos_entrega",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_comercio", sa.Integer(), nullable=False),
        sa.Column("id_metodo_entrega", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_alta",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_ultima_modificacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "orden >= 0",
            name=op.f("ck_comercio_metodos_entrega_orden_no_negativo"),
        ),
        sa.ForeignKeyConstraint(
            ["id_comercio"],
            ["comercios.id"],
            name=op.f(
                "fk_comercio_metodos_entrega_id_comercio_comercios"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_metodo_entrega"],
            ["metodos_entrega.id"],
            name=op.f(
                "fk_comercio_metodos_entrega_id_metodo_entrega_metodos_entrega"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_comercio_metodos_entrega"),
        ),
        sa.UniqueConstraint(
            "id_comercio",
            "id_metodo_entrega",
            name="comercio_metodo_unico",
        ),
    )

    op.create_index(
        op.f("ix_comercio_metodos_entrega_id_comercio"),
        "comercio_metodos_entrega",
        ["id_comercio"],
        unique=False,
    )

    op.create_index(
        op.f("ix_comercio_metodos_entrega_id_metodo_entrega"),
        "comercio_metodos_entrega",
        ["id_metodo_entrega"],
        unique=False,
    )

    metodos_entrega_table = sa.table(
        "metodos_entrega",
        sa.column("codigo", sa.String()),
        sa.column("descripcion", sa.String()),
        sa.column("orden", sa.Integer()),
        sa.column("activo", sa.Boolean()),
    )

    op.bulk_insert(
        metodos_entrega_table,
        [
            {
                "codigo": "retiro_local",
                "descripcion": "Retiro en el local",
                "orden": 1,
                "activo": True,
            },
            {
                "codigo": "delivery",
                "descripcion": "Delivery",
                "orden": 2,
                "activo": True,
            },
            {
                "codigo": "consumo_en_salon",
                "descripcion": "Consumo en el salón",
                "orden": 3,
                "activo": True,
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_comercio_metodos_entrega_id_metodo_entrega"),
        table_name="comercio_metodos_entrega",
    )
    op.drop_index(
        op.f("ix_comercio_metodos_entrega_id_comercio"),
        table_name="comercio_metodos_entrega",
    )
    op.drop_table("comercio_metodos_entrega")

    op.drop_index(
        op.f("ix_metodos_entrega_codigo"),
        table_name="metodos_entrega",
    )
    op.drop_table("metodos_entrega")