"""presentaciones por comercio

Revision ID: 769c71427f34
Revises: 5418353a3820
Create Date: 2026-07-15 23:05:20.641049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769c71427f34'
down_revision: Union[str, Sequence[str], None] = '5418353a3820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentaciones', sa.Column('id_comercio', sa.Integer(), nullable=False))
    op.add_column('presentaciones', sa.Column('orden', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_presentaciones_codigo'), table_name='presentaciones')
    op.create_unique_constraint('comercio_presentacion_codigo_unico', 'presentaciones', ['id_comercio', 'codigo'])
    op.create_unique_constraint('comercio_presentacion_descripcion_unica', 'presentaciones', ['id_comercio', 'descripcion'])
    op.create_index(op.f('ix_presentaciones_id_comercio'), 'presentaciones', ['id_comercio'], unique=False)
    op.create_foreign_key(op.f('fk_presentaciones_id_comercio_comercios'), 'presentaciones', 'comercios', ['id_comercio'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_presentaciones_id_comercio_comercios'), 'presentaciones', type_='foreignkey')
    op.drop_index(op.f('ix_presentaciones_id_comercio'), table_name='presentaciones')
    op.drop_constraint('comercio_presentacion_descripcion_unica', 'presentaciones', type_='unique')
    op.drop_constraint('comercio_presentacion_codigo_unico', 'presentaciones', type_='unique')
    op.create_index(op.f('ix_presentaciones_codigo'), 'presentaciones', ['codigo'], unique=True)
    op.drop_column('presentaciones', 'orden')
    op.drop_column('presentaciones', 'id_comercio')
    # ### end Alembic commands ###
