"""crear presentaciones de productos

Revision ID: 8c69bc3e8bfb
Revises: ec92a0732308
Create Date: 2026-07-14 22:14:17.878096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c69bc3e8bfb'
down_revision: Union[str, Sequence[str], None] = 'ec92a0732308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presentaciones'))
    )
    op.create_index(op.f('ix_presentaciones_codigo'), 'presentaciones', ['codigo'], unique=True)
    op.create_table('producto_presentaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_presentacion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name=op.f('ck_producto_presentaciones_orden_no_negativo')),
    sa.ForeignKeyConstraint(['id_presentacion'], ['presentaciones.id'], name=op.f('fk_producto_presentaciones_id_presentacion_presentaciones'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('fk_producto_presentaciones_id_producto_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_presentaciones')),
    sa.UniqueConstraint('id_producto', 'id_presentacion', name='producto_presentacion_unica')
    )
    op.create_index(op.f('ix_producto_presentaciones_id_presentacion'), 'producto_presentaciones', ['id_presentacion'], unique=False)
    op.create_index(op.f('ix_producto_presentaciones_id_producto'), 'producto_presentaciones', ['id_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_presentaciones_id_producto'), table_name='producto_presentaciones')
    op.drop_index(op.f('ix_producto_presentaciones_id_presentacion'), table_name='producto_presentaciones')
    op.drop_table('producto_presentaciones')
    op.drop_index(op.f('ix_presentaciones_codigo'), table_name='presentaciones')
    op.drop_table('presentaciones')
    # ### end Alembic commands ###
