"""crear medios de pago

Revision ID: 9acd4a7a67d3
Revises: e3ee448f3fa7
Create Date: 2026-07-14 17:05:33.239824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acd4a7a67d3'
down_revision: Union[str, Sequence[str], None] = 'e3ee448f3fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medios_pago'))
    )
    op.create_index(op.f('ix_medios_pago_codigo'), 'medios_pago', ['codigo'], unique=True)
    op.create_table('comercio_medios_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('titular', sa.String(length=150), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], name=op.f('fk_comercio_medios_pago_id_comercio_comercios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medios_pago.id'], name=op.f('fk_comercio_medios_pago_id_medio_pago_medios_pago'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comercio_medios_pago')),
    sa.UniqueConstraint('id_comercio', 'id_medio_pago', name='comercio_medio_pago_unico')
    )
    op.create_index(op.f('ix_comercio_medios_pago_id_comercio'), 'comercio_medios_pago', ['id_comercio'], unique=False)
    op.create_index(op.f('ix_comercio_medios_pago_id_medio_pago'), 'comercio_medios_pago', ['id_medio_pago'], unique=False)
    op.drop_constraint(op.f('uq_metodos_entrega_codigo'), 'metodos_entrega', type_='unique')
    medios_pago_table = sa.table(
    "medios_pago",
    sa.column("codigo", sa.String()),
    sa.column("descripcion", sa.String()),
    sa.column("activo", sa.Boolean()),
)

    op.bulk_insert(
        medios_pago_table,
        [
            {
                "codigo": "efectivo",
                "descripcion": "Efectivo",
                "activo": True,
            },
            {
                "codigo": "debito",
                "descripcion": "Tarjeta de débito",
                "activo": True,
            },
            {
                "codigo": "transferencia",
                "descripcion": "Transferencia",
                "activo": True,
            },
        ],
    )
    
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO comercio_medios_pago
            (id_comercio, id_medio_pago, activo, titular, alias)
        SELECT
            c.id,
            mp.id,
            true,
            NULL,
            NULL
        FROM comercios AS c
        JOIN medios_pago AS mp
            ON mp.codigo = 'efectivo'
        WHERE c.slug = 'supernova-pizza'
        """
    )

    op.execute(
        """
        INSERT INTO comercio_medios_pago
            (id_comercio, id_medio_pago, activo, titular, alias)
        SELECT
            c.id,
            mp.id,
            false,
            NULL,
            NULL
        FROM comercios AS c
        JOIN medios_pago AS mp
            ON mp.codigo = 'debito'
        WHERE c.slug = 'supernova-pizza'
        """
    )

    op.execute(
        """
        INSERT INTO comercio_medios_pago
            (id_comercio, id_medio_pago, activo, titular, alias)
        SELECT
            c.id,
            mp.id,
            true,
            'Alberto Mosquera',
            'supernova.mp'
        FROM comercios AS c
        JOIN medios_pago AS mp
            ON mp.codigo = 'transferencia'
        WHERE c.slug = 'supernova-pizza'
        """
    )

def downgrade() -> None:
    op.drop_index(
        op.f("ix_comercio_medios_pago_id_medio_pago"),
        table_name="comercio_medios_pago",
    )

    op.drop_index(
        op.f("ix_comercio_medios_pago_id_comercio"),
        table_name="comercio_medios_pago",
    )

    op.drop_table("comercio_medios_pago")

    op.drop_index(
        op.f("ix_medios_pago_codigo"),
        table_name="medios_pago",
    )

    op.drop_table("medios_pago")