"""crear categorias de productos

Revision ID: c80ae1ace608
Revises: 9acd4a7a67d3
Create Date: 2026-07-14 17:26:26.126798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80ae1ace608'
down_revision: Union[str, Sequence[str], None] = '9acd4a7a67d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name=op.f('ck_categorias_productos_orden_no_negativo')),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], name=op.f('fk_categorias_productos_id_comercio_comercios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias_productos')),
    sa.UniqueConstraint('id_comercio', 'descripcion', name='comercio_categoria_producto_unica')
    )
    op.create_index(op.f('ix_categorias_productos_id_comercio'), 'categorias_productos', ['id_comercio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorias_productos_id_comercio'), table_name='categorias_productos')
    op.drop_table('categorias_productos')
    # ### end Alembic commands ###
