"""crear precios de productos

Revision ID: e55cac3d6c61
Revises: 8c69bc3e8bfb
Create Date: 2026-07-15 08:29:45.074911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55cac3d6c61'
down_revision: Union[str, Sequence[str], None] = '8c69bc3e8bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto_presentacion', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigencia_desde', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio >= 0', name=op.f('ck_producto_precios_precio_no_negativo')),
    sa.CheckConstraint('vigencia_hasta IS NULL OR vigencia_hasta > vigencia_desde', name=op.f('ck_producto_precios_vigencia_valida')),
    sa.ForeignKeyConstraint(['id_producto_presentacion'], ['producto_presentaciones.id'], name=op.f('fk_producto_precios_id_producto_presentacion_producto_presentaciones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_precios'))
    )
    op.create_index(op.f('ix_producto_precios_id_producto_presentacion'), 'producto_precios', ['id_producto_presentacion'], unique=False)
    op.create_index('uq_producto_precios_precio_vigente', 'producto_precios', ['id_producto_presentacion'], unique=True, postgresql_where=sa.text('vigencia_hasta IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_producto_precios_precio_vigente', table_name='producto_precios', postgresql_where=sa.text('vigencia_hasta IS NULL'))
    op.drop_index(op.f('ix_producto_precios_id_producto_presentacion'), table_name='producto_precios')
    op.drop_table('producto_precios')
    # ### end Alembic commands ###
