"""crear productos

Revision ID: ec92a0732308
Revises: c80ae1ace608
Create Date: 2026-07-14 21:53:12.532136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec92a0732308'
down_revision: Union[str, Sequence[str], None] = 'c80ae1ace608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name=op.f('ck_productos_orden_no_negativo')),
    sa.ForeignKeyConstraint(['id_categoria_producto'], ['categorias_productos.id'], name=op.f('fk_productos_id_categoria_producto_categorias_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos')),
    sa.UniqueConstraint('id_categoria_producto', 'nombre', name='categoria_producto_nombre_unico')
    )
    op.create_index(op.f('ix_productos_id_categoria_producto'), 'productos', ['id_categoria_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_id_categoria_producto'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
